apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

resources:
  - media-namespace.yaml
  - pv/movies-pv.yaml
  - pv/tv-pv.yaml
  - pv/music-pv.yaml
  - pv/download-pv.yaml

  - pvc/movies-pvc.yaml
  - pvc/tv-pvc.yaml
  - pvc/music-pvc.yaml
  - pvc/download-pvc.yaml

commonLabels:
  stack: media

