apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

resources:
  - media-namespace.yaml

  - pv/config-pv.yaml
  - pv/download-pv.yaml
  - pv/movies-pv.yaml
  - pv/music-pv.yaml
  - pv/tv-pv.yaml

  - pvc/config-pvc.yaml
  - pvc/download-pvc.yaml
  - pvc/movies-pvc.yaml
  - pvc/music-pvc.yaml
  - pvc/tv-pvc.yaml

  - apps/plex-media-server.yaml
  - apps/sabnzbd-media-server.yaml
  - apps/sonarr-media-server.yaml
  - apps/radarr-media-server.yaml
  - apps/libdarr-media-server.yaml
   - apps/tautulli-media-server.yaml
  - apps/lidarr-media-server.yaml
  - apps/bazarr-media-server.yaml

commonLabels:
  stack: media

