apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

resources:
  - media-namespace.yaml

  - pv/config-pv.yaml
  # - pvc/download-pvc.yaml
  - pv/movies-pv.yaml
  - pv/music-pv.yaml
  - pv/tv-pv.yaml

  - pvc/config-pvc.yaml
  # - pvc/download-pvc.yaml
  - pvc/movies-pvc.yaml
  - pvc/music-pvc.yaml
  - pvc/tv-pvc.yaml

  - apps/plex-media-server.yaml

commonLabels:
  stack: media

