apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dirt

resources:
  - dirt-namespace.yaml

  - pv/dirt-pv.yaml

  - pvc/dirt-pvc.yaml

  - apps/stashapp-dirt-server.yaml
  - apps/whisparr-dirt-server.yaml
  
commonLabels:
  stack: dirt

