apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dirt

resources:
  - dirt-namespace.yaml

  - pv/dirt-pv.yaml

  - pvc/dirt-pvc.yaml

  - apps/stashapp-server.yaml

  
commonLabels:
  stack: dirt

